version: "3"
services:
  nginx:
    image: "node_test-performance_nginx:latest"
    build:
      context: ../
      dockerfile: docker/performance_nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    container_name: node_test-performance_nginx
    volumes:
      - "/home/cra-arc-user/UPD-Express-Angular/public:/var/www/html"
  web:
    image: "node_test-performance_web:latest"
    container_name: node_test-performance_web
    build:
      context: ../
      dockerfile: docker/performance_web/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    ports:
      - "9000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/Test
    depends_on:
      - mongodb
  mongodb:
    image: lega0208/upd-express-angular:node_test-mongo
    container_name: node_test-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container-test:/data/db
volumes:
  mongodb_data_container-test:
